# Generated by Django 2.0.2 on 2018-03-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='typeUser',
        ),
    ]
